export type ChainOption = { label: string; value: string; disabled?: boolean };

export const EVM_CHAIN_OPTIONS: ChainOption[] = [
  { label: "Select network", value: "" },

  // ── Mainnets ──────────────────────────────────────────────────────────────
  { label: "── Mainnets ──", value: "_group_mainnet", disabled: true },
  { label: "ADI Mainnet", value: "adi-mainnet" },
  { label: "Arbitrum One", value: "ethereum-mainnet-arbitrum-1" },
  { label: "Avalanche", value: "avalanche-mainnet" },
  { label: "Base", value: "ethereum-mainnet-base-1" },
  { label: "BNB Smart Chain", value: "binance_smart_chain-mainnet" },
  { label: "Celo", value: "celo-mainnet" },
  { label: "Ethereum Mainnet", value: "ethereum-mainnet" },
  { label: "Gnosis Chain", value: "gnosis_chain-mainnet" },
  { label: "Hyperliquid", value: "hyperliquid-mainnet" },
  { label: "Ink", value: "ethereum-mainnet-ink-1" },
  { label: "Jovay", value: "jovay-mainnet" },
  { label: "Linea", value: "ethereum-mainnet-linea-1" },
  { label: "Mantle", value: "ethereum-mainnet-mantle-1" },
  { label: "MegaETH", value: "megaeth-mainnet" },
  { label: "Monad", value: "monad-mainnet" },
  { label: "OP Mainnet", value: "ethereum-mainnet-optimism-1" },
  { label: "Pharos", value: "pharos-mainnet" },
  { label: "Plasma", value: "plasma-mainnet" },
  { label: "Polygon", value: "polygon-mainnet" },
  { label: "Scroll", value: "ethereum-mainnet-scroll-1" },
  { label: "Sonic", value: "sonic-mainnet" },
  { label: "World Chain", value: "ethereum-mainnet-worldchain-1" },
  { label: "XLayer", value: "xlayer-mainnet" },
  { label: "ZKSync Era", value: "ethereum-mainnet-zksync-1" },

  // ── Testnets ──────────────────────────────────────────────────────────────
  { label: "── Testnets ──", value: "_group_testnet", disabled: true },
  { label: "ADI Testnet", value: "adi-testnet" },
  { label: "Apechain Curtis", value: "apechain-testnet-curtis" },
  { label: "Arc Testnet", value: "arc-testnet" },
  { label: "Arbitrum Sepolia", value: "ethereum-testnet-sepolia-arbitrum-1" },
  { label: "Avalanche Fuji", value: "avalanche-testnet-fuji" },
  { label: "Base Sepolia", value: "ethereum-testnet-sepolia-base-1" },
  { label: "BNB Chain Testnet", value: "binance_smart_chain-testnet" },
  { label: "Celo Sepolia", value: "celo-testnet-sepolia" },
  { label: "Cronos Testnet", value: "cronos-testnet" },
  { label: "Ethereum Sepolia", value: "ethereum-testnet-sepolia" },
  { label: "Gnosis Chiado", value: "gnosis-chain-testnet-chiado" },
  { label: "Hyperliquid Testnet", value: "hyperliquid-testnet" },
  { label: "Ink Sepolia", value: "ink-testnet-sepolia" },
  { label: "Jovay Testnet", value: "jovay-testnet" },
  { label: "Linea Sepolia", value: "ethereum-testnet-sepolia-linea-1" },
  { label: "Mantle Sepolia", value: "ethereum-testnet-sepolia-mantle-1" },
  { label: "MegaETH Testnet 2", value: "megaeth-testnet" },
  { label: "Monad Testnet", value: "monad-testnet" },
  { label: "OP Sepolia", value: "ethereum-testnet-sepolia-optimism-1" },
  { label: "Pharos Atlantic Testnet", value: "pharos-testnet-atlantic" },
  { label: "Plasma Testnet", value: "plasma-testnet" },
  { label: "Polygon Amoy", value: "polygon-testnet-amoy" },
  { label: "Robinhood Testnet", value: "robinhood-testnet" },
  { label: "Scroll Sepolia", value: "ethereum-testnet-sepolia-scroll-1" },
  { label: "Sonic Testnet", value: "sonic-testnet" },
  { label: "Stable Testnet", value: "stable-testnet" },
  { label: "T-REX Testnet", value: "trex-testnet" },
  { label: "Tempo Testnet", value: "tempo-testnet" },
  { label: "Unichain Sepolia", value: "ethereum-testnet-sepolia-unichain-1" },
  { label: "World Chain Sepolia", value: "ethereum-testnet-sepolia-worldchain-1" },
  { label: "XLayer Testnet", value: "xlayer-testnet" },
  { label: "ZKSync Era Sepolia", value: "ethereum-testnet-sepolia-zksync-1" },

  { label: "Other (type below)", value: "other" },
];
